### ISSUE TITLE
pyFIt-SNE not keeping up-to-date with FIt-SNE

### ISSUE THREAD

**Issue by dkobak** [KlugerLab/pyFIt-SNE#16]
It looks like pyFIt-SNE was last updated over a year ago which means it does not correspond to the current version of FIt-SNE anymore, right? What is the long-term plan here? Do you want to keep supporting pyFIt-SNE by periodically copying current FIt-SNE into it? Do you want to keep it frozen? I think currently it's a bit confusing.

**Comment by linqiaozhi** [comment]
There are currently three python implementations of FIt-SNE: the python [wrapper](https://github.com/KlugerLab/FIt-SNE/blob/master/fast_tsne.py) that @dkobak wrote, [openTSNE](https://github.com/pavlin-policar/openTSNE) which is available on pip but not FFTW-based, and and pyFIt-SNE (this one) which is available on pip and FFTW based.

I agree that it is confusing, and I am thinking of keeping it frozen (with a clear notice on the front page), unless someone else is able to continue to copy the current FIt-SNE into it. 

This package was actually originally created by @gioelelm, but I have been maintaining it since. Gioele, do you have any thoughts on this?

**Comment by linqiaozhi** [comment]
Or even if not freezing it, to just note on the README/PyPI that it is not updated as regularly, to clear up the confusion.

**Comment by linqiaozhi** [comment]
I updated pyFIt-SNE to have the latest version of FIt-SNE. I will intermittently port the source from FIt-SNE to pyFIt-SNE. I made this clear on the README.

I also added text to the README describing the other two options people have for using FIt-SNE in Python (FIt-SNE's python wrapper and openTSNE). Hopefully that makes it less confusing. 

Please re-open or let me know if you have other thoughts.

**Comment by mdmanurung** [comment]
Is there any plan to update this to version 1.2.1? I find this version is much easier to install on a cluster for those who don't have sudo rights.

**Comment by dkobak** [comment]
@MikhaelManurung FIt-SNE itself is now on conda (currently not for Windows though), so you can  install it via conda, one does not need sudo right for that. (But actually one does not need sudo rights to compile FIt-SNE manually, we have instructions for that on the FIt-SNE front page.)

**Comment by dkobak** [comment]
(That said, of course it'd be good to update to 1.2.1.)

**Comment by mdmanurung** [comment]
Thanks for pointing that out! So is it the pre-compiled binary (that I can call with the wrappers) or an updated pyFIt-SNE?

EDIT: I've figured out how to work with this. Thanks!
