### ISSUE TITLE
syntax error in setup.py

### ISSUE THREAD

**Issue by ShobiStassen** [KlugerLab/pyFIt-SNE#4]
Hi, it seems like there is the letter 'f' in the setup.py file which causes the install to fail. I tried to download the file-package, edit setup.py and then do python setup.py install , but I guess i need to properly compile the C++ code with some kind of g++ command from my directory... which I'm not so sure how to do in conjunction with using the python wrapper. thanks for you help. below is the error message

Collecting fitsne
  Using cached https://files.pythonhosted.org/packages/fb/5d/fea125898f35a254c013d35aae76f181d37389b644a3dfb19e745f0ea48b/fitsne-0.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rthyb24l/fitsne/setup.py", line 16
        download_url=f"https://github.com/KlugerLab/pyFIt-SNE/archive/{__version__}.tar.gz"
                                                                                          ^
    SyntaxError: invalid syntax

**Comment by ShobiStassen** [comment]
i downloaded the repository directly from git and ran the installation, that seemed to work

**Comment by linqiaozhi** [comment]
Thanks for using FIt-SNE, I hope you find it useful!

Python 3 allows the use of f-strings for "formatted string literals" you can check them out [here](https://cito.github.io/blog/f-strings/). They can be used by appending f to the string literal, as is done in that snippet of code you pointed out. 

I presume the first installation failed because perhaps you were using Python 2 which does not understand this syntax. And then when you downloaded the repo directly from git and ran the installation, that used Python3 and it worked. Either that or downloading it directly just bypassed this part of the code that depends on Python3 and it worked for you. We probably could make this part also backwards compatible, but since it seems that Python 3 is being increasingly adopted, I have not gotten around to doing so.

Does this answer your question?

**Comment by ShobiStassen** [comment]
Dear Lin, thanks a lot for your explanation. I'm excited to try FIt_SNE out on some large scale biological cell data, and compare it with LargeVis and a multi-core TSNE.
Shobi
